from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue


def generate_launch_description():
    args = [
        # This launch is intended for the Go2 / LiDAR / control computer only.
        # The OAK + YOLO package should run on the camera/Jetson computer and
        # publish /local_goal_point and /target/status over the ROS 2 network.
        DeclareLaunchArgument('target_frame', default_value='base_link'),
        DeclareLaunchArgument('raw_lidar_topic', default_value='/utlidar/cloud'),
        DeclareLaunchArgument('target_topic', default_value='/local_goal_point'),
        DeclareLaunchArgument('target_status_topic', default_value='/target/status'),
        DeclareLaunchArgument('path_topic', default_value='/path'),
        DeclareLaunchArgument('cmd_vel_topic', default_value='/cmd_vel'),
        DeclareLaunchArgument('sport_request_topic', default_value='/api/sport/request'),
        DeclareLaunchArgument('follower_status_topic', default_value='/go2_follower/status'),
        DeclareLaunchArgument('safety_scan_topic', default_value='/utlidar/transformed_cloud'),
        DeclareLaunchArgument('transformed_lidar_topic', default_value='/utlidar/transformed_cloud'),
        DeclareLaunchArgument('accumulated_cloud_topic', default_value='/utlidar/accumulated_cloud'),
        DeclareLaunchArgument('accumulated_obstacle_grid_topic', default_value='/utlidar/accumulated_obstacle_grid'),
        DeclareLaunchArgument('lidar_frame', default_value='utlidar_lidar'),

        # LiDAR mounting correction. Defaults preserve the original package's pitch.
        DeclareLaunchArgument('lidar_roll', default_value='0.0'),
        DeclareLaunchArgument('lidar_pitch', default_value='2.87'),
        DeclareLaunchArgument('lidar_yaw', default_value='0.0'),
        DeclareLaunchArgument('lidar_x', default_value='0.0'),
        DeclareLaunchArgument('lidar_y', default_value='0.0'),
        DeclareLaunchArgument('lidar_z', default_value='0.0'),
        # Optional residual pitch correction from RANSAC floor fitting in the
        # transformed cloud. This compensates small LiDAR/body pitch errors
        # while preserving the static mounting-pitch default above.
        DeclareLaunchArgument('dynamic_pitch_enabled', default_value='true'),
        DeclareLaunchArgument('dynamic_pitch_alpha', default_value='0.08'),
        DeclareLaunchArgument('dynamic_pitch_max_correction_rad', default_value='0.25'),
        DeclareLaunchArgument('dynamic_pitch_hold_last_on_fail', default_value='true'),
        DeclareLaunchArgument('dynamic_pitch_debug_topic', default_value='/go2_lidar_transformer/debug'),

        # LiDAR moving-window accumulation.
        DeclareLaunchArgument('history_duration', default_value='0.6'),
        DeclareLaunchArgument('max_clouds', default_value='36'),
        DeclareLaunchArgument('accumulator_publish_rate_hz', default_value='30.0'),
        DeclareLaunchArgument('planner_publish_rate_hz', default_value='30.0'),
        DeclareLaunchArgument('ogm_min_points_per_cell', default_value='2'),
        DeclareLaunchArgument('min_obstacle_range_m', default_value='0.3'),
        DeclareLaunchArgument('max_obstacle_range_m', default_value='6.0'),
        # Wireless RViz load control.  The planner does not need the full
        # accumulated cloud topic, so the default is to publish only a
        # downsampled visualization cloud.
        DeclareLaunchArgument('publish_accumulated_cloud', default_value='false'),
        DeclareLaunchArgument('publish_accumulated_debug_cloud', default_value='true'),
        DeclareLaunchArgument('accumulated_debug_cloud_topic', default_value='/utlidar/accumulated_cloud_debug'),
        DeclareLaunchArgument('accumulated_debug_cloud_stride', default_value='6'),
        DeclareLaunchArgument('accumulated_debug_cloud_max_points', default_value='3000'),
        DeclareLaunchArgument('accumulated_debug_cloud_rate_hz', default_value='5.0'),
        DeclareLaunchArgument('publish_accumulator_debug_status', default_value='false'),

        # Planner / follower.
        DeclareLaunchArgument('follow_distance_m', default_value='1.0'),
        DeclareLaunchArgument('grid_resolution_m', default_value='0.1'),
        DeclareLaunchArgument('grid_x_min_m', default_value='-0.3'),
        DeclareLaunchArgument('grid_x_max_m', default_value='4.0'),
        DeclareLaunchArgument('grid_y_min_m', default_value='-2.0'),
        DeclareLaunchArgument('grid_y_max_m', default_value='2.0'),
        DeclareLaunchArgument('safety_radius_m', default_value='0.2'),
        DeclareLaunchArgument('potential_radius_m', default_value='0.95'),
        DeclareLaunchArgument('potential_weight', default_value='4.0'),
        DeclareLaunchArgument('waypoint_potential_threshold', default_value='0.2'),
        # Only points inside this height band are treated as obstacles.
        # +x uses obstacle_z_min_m. -x uses obstacle_z_min_negative_x_m so
        # rear/body-side LiDAR returns can be filtered independently.
        DeclareLaunchArgument('obstacle_z_min_m', default_value='0.1'),
        DeclareLaunchArgument('obstacle_z_min_negative_x_m', default_value='0.05'),
        DeclareLaunchArgument('obstacle_z_max_m', default_value='1.20'),
        # Ground-aware obstacle-map generation. If RANSAC finds the floor, the
        # occupancy grid uses floor-relative height instead of base_link z.
        # If RANSAC fails, the legacy obstacle_z_min/max filters above are used.
        DeclareLaunchArgument('use_ground_ransac_filter', default_value='true'),
        DeclareLaunchArgument('ground_ransac_iterations', default_value='70'),
        DeclareLaunchArgument('ground_ransac_distance_threshold_m', default_value='0.035'),
        DeclareLaunchArgument('ground_ransac_max_sample_points', default_value='1200'),
        DeclareLaunchArgument('ground_min_inliers', default_value='100'),
        DeclareLaunchArgument('ground_min_inlier_ratio', default_value='0.10'),
        DeclareLaunchArgument('ground_normal_min_z', default_value='0.70'),
        DeclareLaunchArgument('ground_candidate_x_min_m', default_value='-0.5'),
        DeclareLaunchArgument('ground_candidate_x_max_m', default_value='4.0'),
        DeclareLaunchArgument('ground_candidate_y_abs_m', default_value='2.0'),
        DeclareLaunchArgument('ground_candidate_z_min_m', default_value='-0.45'),
        DeclareLaunchArgument('ground_candidate_z_max_m', default_value='0.35'),
        DeclareLaunchArgument('ground_non_center_min_height_m', default_value='0.04'),
        DeclareLaunchArgument('ground_center_strip_y_abs_m', default_value='0.30'),
        DeclareLaunchArgument('ground_center_strip_min_height_m', default_value='0.10'),
        DeclareLaunchArgument('ground_filter_max_height_m', default_value='1.20'),
        # Exclude low self/leg LiDAR returns in a tunable rear-side cuboid
        # from the 2-D obstacle map.  The cuboid is centered behind base_link
        # by default: x=-0.10 m, x-size=0.30 m, |y|<=0.20 m, floor~0.30 m.
        DeclareLaunchArgument('rear_self_filter_enabled', default_value='true'),
        DeclareLaunchArgument('rear_self_filter_x_center_m', default_value='-0.20'),
        DeclareLaunchArgument('rear_self_filter_x_size_m', default_value='0.40'),
        DeclareLaunchArgument('rear_self_filter_y_abs_m', default_value='0.40'),
        DeclareLaunchArgument('rear_self_filter_height_m', default_value='0.40'),
        DeclareLaunchArgument('publish_rear_self_filter_visualization', default_value='false'),
        DeclareLaunchArgument('rear_self_filter_marker_topic', default_value='/rear_self_filter/box'),
        DeclareLaunchArgument('rear_self_filter_points_topic', default_value='/rear_self_filter/filtered_points'),
        # Planner topic names and auxiliary visualization/status topics.
        # All optional topic switches are explicitly listed here, even when disabled.
        DeclareLaunchArgument('goal_waypoint_topic', default_value='/goal_waypoint'),
        DeclareLaunchArgument('goal_target_topic', default_value='/goal_target'),
        DeclareLaunchArgument('local_obstacle_cloud_topic', default_value='/local_obstacles'),
        DeclareLaunchArgument('local_obstacle_grid_topic', default_value='/local_obstacle_grid'),
        DeclareLaunchArgument('local_potential_grid_topic', default_value='/local_potential_grid'),
        DeclareLaunchArgument('occupied_threshold', default_value='50'),
        DeclareLaunchArgument('max_path_length_m', default_value='4.0'),
        DeclareLaunchArgument('path_resolution_m', default_value='0.20'),
        DeclareLaunchArgument('astar_max_expansions', default_value='12000'),
        DeclareLaunchArgument('prefer_forward_motion', default_value='true'),
        # Planner/follower auxiliary visualization/status topics.  Keep the
        # topics currently used in RViz enabled, and disable side debug topics
        # by default.
        DeclareLaunchArgument('publish_dynamic_pitch_debug', default_value='false'),
        DeclareLaunchArgument('publish_goal_target', default_value='false'),
        DeclareLaunchArgument('publish_local_obstacle_cloud', default_value='false'),
        DeclareLaunchArgument('publish_local_obstacle_grid', default_value='false'),
        DeclareLaunchArgument('publish_local_potential_grid', default_value='true'),
        DeclareLaunchArgument('publish_follower_status', default_value='false'),
        DeclareLaunchArgument('follower_publish_rate_hz', default_value='30.0'),
        DeclareLaunchArgument('manual_release_when_no_target', default_value='true'),
        DeclareLaunchArgument('send_stop_on_release', default_value='true'),
        DeclareLaunchArgument('status_stale_timeout_s', default_value='1.0'),
        DeclareLaunchArgument('goal_tolerance_m', default_value='0.18'),
        DeclareLaunchArgument('lookahead_distance_m', default_value='0.45'),
        DeclareLaunchArgument('api_control_enabled', default_value='true'),
        DeclareLaunchArgument('require_target_status', default_value='false'),
        DeclareLaunchArgument('clear_target_on_status_lost', default_value='true'),
        DeclareLaunchArgument('max_forward_speed_mps', default_value='3.0'),
        DeclareLaunchArgument('max_lateral_speed_mps', default_value='0.5'),
        DeclareLaunchArgument('distance_pid_kp', default_value='0.70'),
        DeclareLaunchArgument('distance_pid_ki', default_value='0.0'),
        DeclareLaunchArgument('distance_pid_kd', default_value='0.08'),
        DeclareLaunchArgument('distance_integral_limit', default_value='1.0'),
        DeclareLaunchArgument('min_tracking_speed_mps', default_value='0.12'),
        DeclareLaunchArgument('linear_accel_limit_mps2', default_value='1.5'),
        DeclareLaunchArgument('linear_decel_limit_mps2', default_value='4.0'),
        DeclareLaunchArgument('high_speed_safety_enabled', default_value='true'),
        DeclareLaunchArgument('require_fresh_safety_lidar', default_value='false'),
        DeclareLaunchArgument('motion_speed_limits_enabled', default_value='true'),
        DeclareLaunchArgument('obstacle_safety_enabled', default_value='true'),
        DeclareLaunchArgument('safety_scan_timeout_s', default_value='0.15'),
        DeclareLaunchArgument('robot_collision_radius_m', default_value='0.32'),
        DeclareLaunchArgument('obstacle_stop_margin_m', default_value='0.45'),
        DeclareLaunchArgument('control_reaction_time_s', default_value='0.20'),
        DeclareLaunchArgument('max_braking_decel_mps2', default_value='4.0'),
        DeclareLaunchArgument('ttc_emergency_stop_s', default_value='0.5'),
        DeclareLaunchArgument('data_age_slowdown_s', default_value='0.20'),
        DeclareLaunchArgument('stale_data_speed_limit_mps', default_value='0.80'),
        DeclareLaunchArgument('turn_slowdown_start_rad', default_value='0.18'),
        DeclareLaunchArgument('turn_speed_limit_heading_rad', default_value='0.35'),
        DeclareLaunchArgument('max_turning_speed_mps', default_value='0.8'),
        DeclareLaunchArgument('slowdown_yaw_error_rad', default_value='0.65'),
        # Only a collision-imminent obstacle triggers a hard stop. Obstacles
        # farther away are handled by A* and can produce lateral body motion.
        DeclareLaunchArgument('emergency_stop_distance_m', default_value='0.6'),
        # Yaw damping. These defaults intentionally prioritize stable following
        # over exact pixel-center alignment because YOLO/depth target points jitter.
        DeclareLaunchArgument('yaw_gain', default_value='0.9'),
        DeclareLaunchArgument('max_yaw_rate_rps', default_value='0.55'),
        DeclareLaunchArgument('yaw_deadband_rad', default_value='0.12'),
        DeclareLaunchArgument('yaw_filter_alpha', default_value='0.25'),
        DeclareLaunchArgument('yaw_slew_rate_limit_rps2', default_value='1.2'),
        DeclareLaunchArgument('yaw_hold_when_close', default_value='true'),
        DeclareLaunchArgument('target_stale_timeout_s', default_value='2.0'),
        DeclareLaunchArgument('path_stale_timeout_s', default_value='1.5'),
    ]

    lidar_transformer = Node(
        package='go2_lidar_planner',
        executable='lidar_transformer_node',
        name='go2_lidar_transformer',
        output='screen',
        parameters=[{
            'input_topic': LaunchConfiguration('raw_lidar_topic'),
            'output_topic': LaunchConfiguration('transformed_lidar_topic'),
            'lidar_frame': LaunchConfiguration('lidar_frame'),
            'target_frame': LaunchConfiguration('target_frame'),
            'lidar_roll': ParameterValue(LaunchConfiguration('lidar_roll'), value_type=float),
            'lidar_pitch': ParameterValue(LaunchConfiguration('lidar_pitch'), value_type=float),
            'lidar_yaw': ParameterValue(LaunchConfiguration('lidar_yaw'), value_type=float),
            'lidar_x': ParameterValue(LaunchConfiguration('lidar_x'), value_type=float),
            'lidar_y': ParameterValue(LaunchConfiguration('lidar_y'), value_type=float),
            'lidar_z': ParameterValue(LaunchConfiguration('lidar_z'), value_type=float),
            'dynamic_pitch_enabled': ParameterValue(LaunchConfiguration('dynamic_pitch_enabled'), value_type=bool),
            'dynamic_pitch_alpha': ParameterValue(LaunchConfiguration('dynamic_pitch_alpha'), value_type=float),
            'dynamic_pitch_max_correction_rad': ParameterValue(LaunchConfiguration('dynamic_pitch_max_correction_rad'), value_type=float),
            'dynamic_pitch_hold_last_on_fail': ParameterValue(LaunchConfiguration('dynamic_pitch_hold_last_on_fail'), value_type=bool),
            'dynamic_pitch_debug_topic': LaunchConfiguration('dynamic_pitch_debug_topic'),
            'publish_dynamic_pitch_debug': ParameterValue(LaunchConfiguration('publish_dynamic_pitch_debug'), value_type=bool),
            'ground_ransac_iterations': ParameterValue(LaunchConfiguration('ground_ransac_iterations'), value_type=int),
            'ground_ransac_distance_threshold_m': ParameterValue(LaunchConfiguration('ground_ransac_distance_threshold_m'), value_type=float),
            'ground_ransac_max_sample_points': ParameterValue(LaunchConfiguration('ground_ransac_max_sample_points'), value_type=int),
            'ground_min_inliers': ParameterValue(LaunchConfiguration('ground_min_inliers'), value_type=int),
            'ground_min_inlier_ratio': ParameterValue(LaunchConfiguration('ground_min_inlier_ratio'), value_type=float),
            'ground_normal_min_z': ParameterValue(LaunchConfiguration('ground_normal_min_z'), value_type=float),
            'ground_candidate_x_min_m': ParameterValue(LaunchConfiguration('ground_candidate_x_min_m'), value_type=float),
            'ground_candidate_x_max_m': ParameterValue(LaunchConfiguration('ground_candidate_x_max_m'), value_type=float),
            'ground_candidate_y_abs_m': ParameterValue(LaunchConfiguration('ground_candidate_y_abs_m'), value_type=float),
            'ground_candidate_z_min_m': ParameterValue(LaunchConfiguration('ground_candidate_z_min_m'), value_type=float),
            'ground_candidate_z_max_m': ParameterValue(LaunchConfiguration('ground_candidate_z_max_m'), value_type=float),
        }],
    )

    accumulator = Node(
        package='go2_lidar_planner',
        executable='lidar_accumulator_node',
        name='go2_lidar_accumulator',
        output='screen',
        parameters=[{
            'input_topic': LaunchConfiguration('transformed_lidar_topic'),
            'output_topic': LaunchConfiguration('accumulated_cloud_topic'),
            'publish_accumulated_cloud': ParameterValue(LaunchConfiguration('publish_accumulated_cloud'), value_type=bool),
            'publish_accumulated_debug_cloud': ParameterValue(LaunchConfiguration('publish_accumulated_debug_cloud'), value_type=bool),
            'accumulated_debug_cloud_topic': LaunchConfiguration('accumulated_debug_cloud_topic'),
            'accumulated_debug_cloud_stride': ParameterValue(LaunchConfiguration('accumulated_debug_cloud_stride'), value_type=int),
            'accumulated_debug_cloud_max_points': ParameterValue(LaunchConfiguration('accumulated_debug_cloud_max_points'), value_type=int),
            'accumulated_debug_cloud_rate_hz': ParameterValue(LaunchConfiguration('accumulated_debug_cloud_rate_hz'), value_type=float),
            'publish_accumulator_debug_status': ParameterValue(LaunchConfiguration('publish_accumulator_debug_status'), value_type=bool),
            'history_duration': ParameterValue(LaunchConfiguration('history_duration'), value_type=float),
            'max_clouds': ParameterValue(LaunchConfiguration('max_clouds'), value_type=int),
            'publish_rate_hz': ParameterValue(LaunchConfiguration('accumulator_publish_rate_hz'), value_type=float),
            'occupancy_grid_topic': LaunchConfiguration('accumulated_obstacle_grid_topic'),
            'grid_resolution_m': ParameterValue(LaunchConfiguration('grid_resolution_m'), value_type=float),
            'grid_x_min_m': ParameterValue(LaunchConfiguration('grid_x_min_m'), value_type=float),
            'grid_x_max_m': ParameterValue(LaunchConfiguration('grid_x_max_m'), value_type=float),
            'grid_y_min_m': ParameterValue(LaunchConfiguration('grid_y_min_m'), value_type=float),
            'grid_y_max_m': ParameterValue(LaunchConfiguration('grid_y_max_m'), value_type=float),
            'obstacle_z_min_m': ParameterValue(LaunchConfiguration('obstacle_z_min_m'), value_type=float),
            'obstacle_z_min_negative_x_m': ParameterValue(LaunchConfiguration('obstacle_z_min_negative_x_m'), value_type=float),
            'obstacle_z_max_m': ParameterValue(LaunchConfiguration('obstacle_z_max_m'), value_type=float),
            'min_obstacle_range_m': ParameterValue(LaunchConfiguration('min_obstacle_range_m'), value_type=float),
            'max_obstacle_range_m': ParameterValue(LaunchConfiguration('max_obstacle_range_m'), value_type=float),
            'min_points_per_cell': ParameterValue(LaunchConfiguration('ogm_min_points_per_cell'), value_type=int),
            'use_ground_ransac_filter': ParameterValue(LaunchConfiguration('use_ground_ransac_filter'), value_type=bool),
            'ground_ransac_iterations': ParameterValue(LaunchConfiguration('ground_ransac_iterations'), value_type=int),
            'ground_ransac_distance_threshold_m': ParameterValue(LaunchConfiguration('ground_ransac_distance_threshold_m'), value_type=float),
            'ground_ransac_max_sample_points': ParameterValue(LaunchConfiguration('ground_ransac_max_sample_points'), value_type=int),
            'ground_min_inliers': ParameterValue(LaunchConfiguration('ground_min_inliers'), value_type=int),
            'ground_min_inlier_ratio': ParameterValue(LaunchConfiguration('ground_min_inlier_ratio'), value_type=float),
            'ground_normal_min_z': ParameterValue(LaunchConfiguration('ground_normal_min_z'), value_type=float),
            'ground_candidate_x_min_m': ParameterValue(LaunchConfiguration('ground_candidate_x_min_m'), value_type=float),
            'ground_candidate_x_max_m': ParameterValue(LaunchConfiguration('ground_candidate_x_max_m'), value_type=float),
            'ground_candidate_y_abs_m': ParameterValue(LaunchConfiguration('ground_candidate_y_abs_m'), value_type=float),
            'ground_candidate_z_min_m': ParameterValue(LaunchConfiguration('ground_candidate_z_min_m'), value_type=float),
            'ground_candidate_z_max_m': ParameterValue(LaunchConfiguration('ground_candidate_z_max_m'), value_type=float),
            'ground_non_center_min_height_m': ParameterValue(LaunchConfiguration('ground_non_center_min_height_m'), value_type=float),
            'ground_center_strip_y_abs_m': ParameterValue(LaunchConfiguration('ground_center_strip_y_abs_m'), value_type=float),
            'ground_center_strip_min_height_m': ParameterValue(LaunchConfiguration('ground_center_strip_min_height_m'), value_type=float),
            'ground_filter_max_height_m': ParameterValue(LaunchConfiguration('ground_filter_max_height_m'), value_type=float),
            'rear_self_filter_enabled': ParameterValue(LaunchConfiguration('rear_self_filter_enabled'), value_type=bool),
            'rear_self_filter_x_center_m': ParameterValue(LaunchConfiguration('rear_self_filter_x_center_m'), value_type=float),
            'rear_self_filter_x_size_m': ParameterValue(LaunchConfiguration('rear_self_filter_x_size_m'), value_type=float),
            'rear_self_filter_y_abs_m': ParameterValue(LaunchConfiguration('rear_self_filter_y_abs_m'), value_type=float),
            'rear_self_filter_height_m': ParameterValue(LaunchConfiguration('rear_self_filter_height_m'), value_type=float),
            'publish_rear_self_filter_visualization': ParameterValue(LaunchConfiguration('publish_rear_self_filter_visualization'), value_type=bool),
            'rear_self_filter_marker_topic': LaunchConfiguration('rear_self_filter_marker_topic'),
            'rear_self_filter_points_topic': LaunchConfiguration('rear_self_filter_points_topic'),
        }],
    )


    planner = Node(
        package='go2_lidar_planner',
        executable='potential_astar_planner_node',
        name='go2_potential_astar_planner',
        output='screen',
        parameters=[{
            'path_frame': LaunchConfiguration('target_frame'),
            'target_topic': LaunchConfiguration('target_topic'),
            'target_status_topic': LaunchConfiguration('target_status_topic'),
            'clear_target_on_status_lost': ParameterValue(LaunchConfiguration('clear_target_on_status_lost'), value_type=bool),
            'occupancy_input_topic': LaunchConfiguration('accumulated_obstacle_grid_topic'),
            'path_topic': LaunchConfiguration('path_topic'),
            'goal_waypoint_topic': LaunchConfiguration('goal_waypoint_topic'),
            'goal_target_topic': LaunchConfiguration('goal_target_topic'),
            'obstacle_cloud_topic': LaunchConfiguration('local_obstacle_cloud_topic'),
            'occupancy_grid_topic': LaunchConfiguration('local_obstacle_grid_topic'),
            'potential_grid_topic': LaunchConfiguration('local_potential_grid_topic'),
            'occupied_threshold': ParameterValue(LaunchConfiguration('occupied_threshold'), value_type=int),
            'publish_goal_target': ParameterValue(LaunchConfiguration('publish_goal_target'), value_type=bool),
            'publish_local_obstacle_cloud': ParameterValue(LaunchConfiguration('publish_local_obstacle_cloud'), value_type=bool),
            'publish_local_obstacle_grid': ParameterValue(LaunchConfiguration('publish_local_obstacle_grid'), value_type=bool),
            'publish_local_potential_grid': ParameterValue(LaunchConfiguration('publish_local_potential_grid'), value_type=bool),
            'publish_rate_hz': ParameterValue(LaunchConfiguration('planner_publish_rate_hz'), value_type=float),
            'follow_distance_m': ParameterValue(LaunchConfiguration('follow_distance_m'), value_type=float),
            'max_path_length_m': ParameterValue(LaunchConfiguration('max_path_length_m'), value_type=float),
            'path_resolution_m': ParameterValue(LaunchConfiguration('path_resolution_m'), value_type=float),
            'grid_resolution_m': ParameterValue(LaunchConfiguration('grid_resolution_m'), value_type=float),
            'grid_x_min_m': ParameterValue(LaunchConfiguration('grid_x_min_m'), value_type=float),
            'grid_x_max_m': ParameterValue(LaunchConfiguration('grid_x_max_m'), value_type=float),
            'grid_y_min_m': ParameterValue(LaunchConfiguration('grid_y_min_m'), value_type=float),
            'grid_y_max_m': ParameterValue(LaunchConfiguration('grid_y_max_m'), value_type=float),
            'safety_radius_m': ParameterValue(LaunchConfiguration('safety_radius_m'), value_type=float),
            'potential_radius_m': ParameterValue(LaunchConfiguration('potential_radius_m'), value_type=float),
            'potential_weight': ParameterValue(LaunchConfiguration('potential_weight'), value_type=float),
            'waypoint_potential_threshold': ParameterValue(LaunchConfiguration('waypoint_potential_threshold'), value_type=float),
            'astar_max_expansions': ParameterValue(LaunchConfiguration('astar_max_expansions'), value_type=int),
            'prefer_forward_motion': ParameterValue(LaunchConfiguration('prefer_forward_motion'), value_type=bool),
            'emergency_stop_distance_m': ParameterValue(LaunchConfiguration('emergency_stop_distance_m'), value_type=float),
            # OAK/YOLO may run on another device and can be slower than LiDAR/control.
            # Use the same target timeout in planner and follower.
            'target_stale_timeout_s': ParameterValue(LaunchConfiguration('target_stale_timeout_s'), value_type=float),
        }],
    )

    follower = Node(
        package='go2_lidar_planner',
        executable='go2_path_follower_node',
        name='go2_path_follower',
        output='screen',
        parameters=[{
            'follow_distance_m': ParameterValue(LaunchConfiguration('follow_distance_m'), value_type=float),
            'publish_rate_hz': ParameterValue(LaunchConfiguration('follower_publish_rate_hz'), value_type=float),
            'manual_release_when_no_target': ParameterValue(LaunchConfiguration('manual_release_when_no_target'), value_type=bool),
            'send_stop_on_release': ParameterValue(LaunchConfiguration('send_stop_on_release'), value_type=bool),
            'status_stale_timeout_s': ParameterValue(LaunchConfiguration('status_stale_timeout_s'), value_type=float),
            'goal_tolerance_m': ParameterValue(LaunchConfiguration('goal_tolerance_m'), value_type=float),
            'lookahead_distance_m': ParameterValue(LaunchConfiguration('lookahead_distance_m'), value_type=float),
            'api_control_enabled': ParameterValue(LaunchConfiguration('api_control_enabled'), value_type=bool),
            'max_forward_speed_mps': ParameterValue(LaunchConfiguration('max_forward_speed_mps'), value_type=float),
            'max_lateral_speed_mps': ParameterValue(LaunchConfiguration('max_lateral_speed_mps'), value_type=float),
            'distance_pid_kp': ParameterValue(LaunchConfiguration('distance_pid_kp'), value_type=float),
            'distance_pid_ki': ParameterValue(LaunchConfiguration('distance_pid_ki'), value_type=float),
            'distance_pid_kd': ParameterValue(LaunchConfiguration('distance_pid_kd'), value_type=float),
            'distance_integral_limit': ParameterValue(LaunchConfiguration('distance_integral_limit'), value_type=float),
            'min_tracking_speed_mps': ParameterValue(LaunchConfiguration('min_tracking_speed_mps'), value_type=float),
            'linear_accel_limit_mps2': ParameterValue(LaunchConfiguration('linear_accel_limit_mps2'), value_type=float),
            'linear_decel_limit_mps2': ParameterValue(LaunchConfiguration('linear_decel_limit_mps2'), value_type=float),
            'high_speed_safety_enabled': ParameterValue(LaunchConfiguration('high_speed_safety_enabled'), value_type=bool),
            'require_fresh_safety_lidar': ParameterValue(LaunchConfiguration('require_fresh_safety_lidar'), value_type=bool),
            'motion_speed_limits_enabled': ParameterValue(LaunchConfiguration('motion_speed_limits_enabled'), value_type=bool),
            'obstacle_safety_enabled': ParameterValue(LaunchConfiguration('obstacle_safety_enabled'), value_type=bool),
            'safety_scan_timeout_s': ParameterValue(LaunchConfiguration('safety_scan_timeout_s'), value_type=float),
            'safety_obstacle_z_min_m': ParameterValue(LaunchConfiguration('obstacle_z_min_m'), value_type=float),
            'safety_obstacle_z_min_negative_x_m': ParameterValue(LaunchConfiguration('obstacle_z_min_negative_x_m'), value_type=float),
            'safety_obstacle_z_max_m': ParameterValue(LaunchConfiguration('obstacle_z_max_m'), value_type=float),
            'min_obstacle_range_m': ParameterValue(LaunchConfiguration('min_obstacle_range_m'), value_type=float),
            'robot_collision_radius_m': ParameterValue(LaunchConfiguration('robot_collision_radius_m'), value_type=float),
            'obstacle_stop_margin_m': ParameterValue(LaunchConfiguration('obstacle_stop_margin_m'), value_type=float),
            'control_reaction_time_s': ParameterValue(LaunchConfiguration('control_reaction_time_s'), value_type=float),
            'max_braking_decel_mps2': ParameterValue(LaunchConfiguration('max_braking_decel_mps2'), value_type=float),
            'ttc_emergency_stop_s': ParameterValue(LaunchConfiguration('ttc_emergency_stop_s'), value_type=float),
            'data_age_slowdown_s': ParameterValue(LaunchConfiguration('data_age_slowdown_s'), value_type=float),
            'stale_data_speed_limit_mps': ParameterValue(LaunchConfiguration('stale_data_speed_limit_mps'), value_type=float),
            'turn_slowdown_start_rad': ParameterValue(LaunchConfiguration('turn_slowdown_start_rad'), value_type=float),
            'turn_speed_limit_heading_rad': ParameterValue(LaunchConfiguration('turn_speed_limit_heading_rad'), value_type=float),
            'max_turning_speed_mps': ParameterValue(LaunchConfiguration('max_turning_speed_mps'), value_type=float),
            'slowdown_yaw_error_rad': ParameterValue(LaunchConfiguration('slowdown_yaw_error_rad'), value_type=float),
            'yaw_gain': ParameterValue(LaunchConfiguration('yaw_gain'), value_type=float),
            'max_yaw_rate_rps': ParameterValue(LaunchConfiguration('max_yaw_rate_rps'), value_type=float),
            'yaw_deadband_rad': ParameterValue(LaunchConfiguration('yaw_deadband_rad'), value_type=float),
            'yaw_filter_alpha': ParameterValue(LaunchConfiguration('yaw_filter_alpha'), value_type=float),
            'yaw_slew_rate_limit_rps2': ParameterValue(LaunchConfiguration('yaw_slew_rate_limit_rps2'), value_type=float),
            'yaw_hold_when_close': ParameterValue(LaunchConfiguration('yaw_hold_when_close'), value_type=bool),
            'target_stale_timeout_s': ParameterValue(LaunchConfiguration('target_stale_timeout_s'), value_type=float),
            'path_stale_timeout_s': ParameterValue(LaunchConfiguration('path_stale_timeout_s'), value_type=float),
            'target_topic': LaunchConfiguration('target_topic'),
            'target_status_topic': LaunchConfiguration('target_status_topic'),
            'path_topic': LaunchConfiguration('path_topic'),
            'cmd_vel_topic': LaunchConfiguration('cmd_vel_topic'),
            'sport_request_topic': LaunchConfiguration('sport_request_topic'),
            'follower_status_topic': LaunchConfiguration('follower_status_topic'),
            'publish_follower_status': ParameterValue(LaunchConfiguration('publish_follower_status'), value_type=bool),
            'safety_scan_topic': LaunchConfiguration('safety_scan_topic'),
            'require_target_status': ParameterValue(LaunchConfiguration('require_target_status'), value_type=bool),
            'clear_target_on_status_lost': ParameterValue(LaunchConfiguration('clear_target_on_status_lost'), value_type=bool),
            'cmd_frame': LaunchConfiguration('target_frame'),
        }],
    )

    return LaunchDescription(args + [lidar_transformer, accumulator, planner, follower])
