#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'go2-lidar-planner','console_scripts','lidar_transformer_node'
__requires__ = 'go2-lidar-planner'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('go2-lidar-planner', 'console_scripts', 'lidar_transformer_node')()
    )
